(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (if (eq? p password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request - MAKE-ACCOUNT" m)))
        (error "Incorrect password")))
  dispatch)

(define (make-joint account origpass newpass)
  (define (dispatch p m)
    (if (eq? p newpass)
      (account origpass m)
      (error "Incorrect joint account password")))
  ((account origpass 'withdraw) 0)
  dispatch)
